VULKAN_SDK = os.getenv("VULKAN_SDK")
PROGRAM_FILES = os.getenv("ProgramW6432")
BOOST_VERSION = "boost_1_84_0"
KABLUNK_DIR = os.getenv("KABLUNK_DIR")

IncludeDir = {}
IncludeDir["stb_image"] = "%{KABLUNK_DIR}/KablunkEngine/vendor/stb_image"
IncludeDir["GLFW"] = "%{KABLUNK_DIR}/KablunkEngine/vendor/GLFW/include"
IncludeDir["Glad"] = "%{KABLUNK_DIR}/KablunkEngine/vendor/Glad/include"
IncludeDir["ImGui"] = "%{KABLUNK_DIR}/KablunkEngine/vendor/imgui"
IncludeDir["glm"] = "%{KABLUNK_DIR}/KablunkEngine/vendor/glm"
IncludeDir["entt"] = "%{KABLUNK_DIR}/KablunkEngine/vendor/entt/include"
IncludeDir["yaml_cpp"] = "%{KABLUNK_DIR}/KablunkEngine/vendor/yaml-cpp/include"
IncludeDir["spdlog"] = "%{KABLUNK_DIR}/KablunkEngine/vendor/spdlog/include"
IncludeDir["stduuid"] = "%{KABLUNK_DIR}/KablunkEngine/vendor/stduuid/include"
IncludeDir["gsl"] = "%{KABLUNK_DIR}/KablunkEngine/vendor/stduuid/gsl"
IncludeDir["ImGuizmo"] = "%{KABLUNK_DIR}/KablunkEngine/vendor/ImGuizmo"
IncludeDir["assimp"] = "%{KABLUNK_DIR}/KablunkEngine/vendor/assimp/include"
IncludeDir["Box2d"] = "%{KABLUNK_DIR}/KablunkEngine/vendor/box2d/include"
IncludeDir["cr"] = "%{KABLUNK_DIR}/KablunkEngine/vendor/cr"
IncludeDir["mono"] = "%{KABLUNK_DIR}/KablunkEngine/vendor/mono/include"
IncludeDir["VulkanSDK"] = "%{VULKAN_SDK}/Include"
IncludeDir["VulkanSDK_LocalInclude"] = "%{KABLUNK_DIR}/KablunkEngine/vendor/VulkanSDK/Include"
-- TODO: should use BOOST_DIR environment variable instead of fixed path...
IncludeDir["boost"] = "%{PROGRAM_FILES}/boost/%{BOOST_VERSION}"
IncludeDir["miniaudio"] = "%{KABLUNK_DIR}/KablunkEngine/vendor/miniaudio/include"
IncludeDir["optick"] = "%{KABLUNK_DIR}/KablunkEngine/vendor/optick/src"
IncludeDir["tl_expected"] = "%{KABLUNK_DIR}/KablunkEngine/vendor/expected/include"
IncludeDir["robin_hood"] = "%{KABLUNK_DIR}/KablunkEngine/vendor/robin-hood/include"
IncludeDir["protobuf"] = "%{KABLUNK_DIR}/KablunkEngine/vendor/protobuf/src"
IncludeDir["absl"] = "%{KABLUNK_DIR}/KablunkEngine/vendor/abseil-cpp/"
-- external fmt lib because of MSVC 17.7 bug
IncludeDir["fmt"] = "%{KABLUNK_DIR}/KablunkEngine/vendor/fmt/include"
IncludeDir["tracy"] = "%{KABLUNK_DIR}/KablunkEngine/vendor/tracy/public"
IncludeDir["GameNetworkingSockets"] = "%{KABLUNK_DIR}/KablunkEngine/vendor/GameNetworkingSockets/include"
IncludeDir["LuaJIT"] = "%{KABLUNK_DIR}/KablunkEngine/vendor/LuaJIT/src"
IncludeDir["Catch2"] = "%{KABLUNK_DIR}/KablunkEngine/vendor/Catch2/extras"
IncludeDir["msdf_atlas_gen"] = "%{KABLUNK_DIR}/KablunkEngine/vendor/msdf-atlas-gen/msdf-atlas-gen"
IncludeDir["msdfgen"] = "%{KABLUNK_DIR}/KablunkEngine/vendor/msdf-atlas-gen/msdfgen"
IncludeDir["tinyxml2"] = "%{KABLUNK_DIR}/KablunkEngine/vendor/tinyxml2"
IncludeDir["freetype"] = "%{KABLUNK_DIR}/KablunkEngine/vendor/msdf-atlas-gen/msdfgen/freetype/include"
IncludeDir["msgpack"] = "%{KABLUNK_DIR}/KablunkEngine/vendor/msgpack-c/include"
IncludeDir["rapidjson"] = "%{KABLUNK_DIR}/KablunkEngine/vendor/rapidjson/include"
IncludeDir["sol2"] = "%{KABLUNK_DIR}/KablunkEngine/vendor/sol2/single/single/include"

LibraryDir = {}
LibraryDir["VulkanSDK"] = "%{VULKAN_SDK}/Lib"
LibraryDir["VulkanSDK_Debug"] = "%{VULKAN_SDK}/Lib"
LibraryDir["VulkanSDK_Bin"] = "%{VULKAN_SDK}/Bin"
LibraryDir["VulkanSDK_Debug_Bin"] = "%{VULKAN_SDK}/Bin"

Library = {}
Library["assimp"] = "%{KABLUNK_DIR}/KablunkEngine/vendor/assimp/bin/debug/assimp-vc143-mtd.lib"
Library["assimp_release"] = "%{KABLUNK_DIR}/KablunkEngine/vendor/assimp/bin/release/assimp-vc143-mt.lib"
Library["mono"] = "%{KABLUNK_DIR}/KablunkEngine/vendor/mono/lib/windows/debug/mono-2.0-sgen.lib"
Library["mono_release"] = "%{KABLUNK_DIR}/KablunkEngine/vendor/mono/lib/windows/release/mono-2.0-sgen.lib"
Library["Vulkan"] = "%{LibraryDir.VulkanSDK}/vulkan-1.lib"
Library["VulkanUtils"] = "%{LibraryDir.VulkanSDK}/VkLayer_utils.lib"
Library["LuaJIT"] = "%{KABLUNK_DIR}/KablunkEngine/vendor/LuaJIT/src/lua51.lib"

Library["ShaderC_Debug"] = "%{LibraryDir.VulkanSDK_Debug}/shaderc_sharedd.lib"
Library["ShaderC_Utils_Debug"] = "%{LibraryDir.VulkanSDK_Debug}/shaderc_utild.lib"
Library["SPIRV_Cross_Debug"] = "%{LibraryDir.VulkanSDK_Debug}/spirv-cross-cored.lib"
Library["SPIRV_Cross_GLSL_Debug"] = "%{LibraryDir.VulkanSDK_Debug}/spirv-cross-glsld.lib"
Library["SPIRV_Tools_Debug"] = "%{LibraryDir.VulkanSDK_Debug}/SPIRV-Toolsd.lib"

Library["ShaderC_Release"] = "%{LibraryDir.VulkanSDK}/shaderc_shared.lib"
Library["ShaderC_Utils_Release"] = "%{LibraryDir.VulkanSDK}/shaderc_util.lib"
Library["SPIRV_Cross_Release"] = "%{LibraryDir.VulkanSDK}/spirv-cross-core.lib"
Library["SPIRV_Cross_GLSL_Release"] = "%{LibraryDir.VulkanSDK}/spirv-cross-glsl.lib"
Library["SPIRV_Tools"] = "%{LibraryDir.VulkanSDK}/SPIRV-Tools.lib"
