#ifndef SANDBOX_CORE_H
#define SANDBOX_CORE_H

// #TODO Remove

#include <Kablunk.h>
//REGISTER_NATIVE_SCRIPT(CameraController);

BEGIN_REGISTER_NATIVE_SCRIPTS()
END_REGISTER_NATIVE_SCRIPTS()


#endif
