#include "Sandbox/ReflectionTest.h"

KB_REFLECT_STRUCT_BEGIN(TestStruct)
KB_REFLECT_STRUCT_DEFINE_MEMBER(a)
KB_REFLECT_STRUCT_DEFINE_MEMBER(b)
KB_REFLECT_STRUCT_DEFINE_MEMBER(c)
KB_REFLECT_STRUCT_DEFINE_MEMBER(d)
KB_REFLECT_STRUCT_END()
